dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .

script:
  # Build for T16 with no extra cmake flags
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx benlye/jumpertx-build

  # Build for T16 with a changed default cmake flag
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=HELI=NO" benlye/jumpertx-build

  # Build for T16 with an additional cmake flag
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR" benlye/jumpertx-build

  # Build for T16 with an additional cmake flag and a default changed
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR HELI=NO" benlye/jumpertx-build

  # Build for T16 with an additional cmake flag, a default changed, and a default the same
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR HELI=NO MULTIMODULE=YES" benlye/jumpertx-build

  # Build for T16HD
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=PCB=T16HD" benlye/jumpertx-build

  # Build for T12
  #- docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=PCB=T12" benlye/jumpertx-build
  
  # Build for German
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=TRANSLATIONS=DE" benlye/jumpertx-build

  # Build for French
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=TRANSLATIONS=FR" benlye/jumpertx-build

  # Build for Czech
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=TRANSLATIONS=CZ" benlye/jumpertx-build
