dist: trusty
sudo: true

language: c

services:
  - docker

notifications:
  email: false

before_install:
  - git clone --recursive https://github.com/JumperXYZ/JumperTX.git /tmp/JumperTX
  
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ls -al
  - docker build -t benlye/jumpertx-build .

script:
  # Build with no extra cmake flags
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi

    # Build with a changed default cmake flag
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=HELI=NO" benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi

    # Build with an additional cmake flag
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR" benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi

    # Build with an additional cmake flag and a default changed
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR HELI=NO" benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi

  # Build with an additional cmake flag, a default changed, and a default the same
  - docker run --rm -it -v /tmp/JumperTX:/jumpertx -e "CMAKE_FLAGS=FOO=BAR HELI=NO MULTIMODULE=YES" benlye/jumpertx-build
  - ls -al /tmp/JumperTX/jumpertx-t16.bin
  - if [ ! -f /tmp/JumperTX/jumpertx-t16.bin ]; then
      exit 1;
    fi